image: docker:20.10
variables:
  GO111MODULE: "on"
  GOCACHE: "/tmp/"
  CGO_ENABLED: 0
  NAME: "h2s"
  REGISTRY: "registry.sanremo.website"
  IMAGE: "$REGISTRY/$NAME"
stages:
  - test
  - build
  - build_docker
  - deploy
test:
  stage: test
  image: golang:1.16-alpine
  script:
    - go mod tidy
    - CGO_ENABLED=0 go vet ./...
    - CGO_ENABLED=0 go test ./...
build_executable:
  stage: build
  image: golang:1.16-alpine
  script:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags \"-static\"' -o h2s cmd/main.go
  artifacts:
    paths:
      - h2s
build_docker_image:
  stage: build_docker
  image: docker:20.10
  script:
    - docker login -p $REGISTRY_PASSWORD -u $REGISTRY_USER $REGISTRY
    - docker build -t $IMAGE:${CI_COMMIT_SHORT_SHA} .
    - docker tag $IMAGE:${CI_COMMIT_SHORT_SHA} $IMAGE:latest
    - docker push $IMAGE:${CI_COMMIT_SHORT_SHA}
deploy:
  stage: deploy
  image: alpine:3.14
  script:
    - apk add curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl
    - chmod +x ./kubectl && mv ./kubectl /usr/local/bin
    - kubectl config set-cluster sanremo --server="https://192.168.0.92:6443"
    - kubectl config set-cluster sanremo --certificate-authority=${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${K8S_TOKEN}"
    - kubectl config set-context default --cluster=sanremo --user=gitlab
    - kubectl config use-context default
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
    - sed -i "s/<BRANCH>/${CI_COMMIT_BRANCH}/g" deployment.yaml
    - sed -i "s/<NAME>/${NAME}/g" deployment.yaml
    - sed -i "s/<REGISTRY>/${REGISTRY}/g" deployment.yaml
    - sed -i "s/<SMTP_HOST>/${SMTP_HOST}/g" deployment.yaml
    - sed -i "s/<SMTP_PORT>/${SMTP_PORT}/g" deployment.yaml
    - sed -i "s/<SMTP_USERNAME>/${SMTP_USERNAME}/g" deployment.yaml
    - sed -i "s/<SMTP_PASSWORD>/${SMTP_PASSWORD}/g" deployment.yaml
    - sed -i "s/<SMTP_SSL>/${SMTP_SSL}/g" deployment.yaml
    - sed -i "s/<SMTP_TSL>/${SMTP_TSL}/g" deployment.yaml
    - cat deployment.yaml
    # - kubectl apply -f deployment.yaml
