---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ecommerce-<BRANCH>
  name: config-<NAME>
data:
  SMTP_HOST: "<SMTP_HOST>"
  SMTP_PORT: <SMTP_PORT>
  SMTP_USERNAME: <SMTP_USERNAME>
  SMTP_PASSWORD: <SMTP_PASSWORD>
  SMTP_SSL: <SMTP_SSL>
  SMTP_TSL: <SMTP_TSL>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ecommerce-<BRANCH>
  name: <NAME>
  labels:
    app: ecommerce
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ecommerce-<NAME>
  template:
    metadata:
      labels:
        app: ecommerce-<NAME>
    spec:
      imagePullSecrets:
        - name: registry
      containers:
        - envFrom:
            - configMapRef:
                name: config-<NAME>
          name: ecommerce-<NAME>
          image: "<REGISTRY>/<NAME>:<VERSION>"
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-<NAME>
  namespace: ecommerce-<BRANCH>
  labels:
    app: ecommerce-<NAME>
spec:
  type: NodePort
  selector:
    app: ecommerce-<NAME>
  ports:
    - port: 8090
      nodePort: 30009