name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o h2s cmd/main.go
      - name: Test
        run: go test -v ./...
      - name: listen dir
        run: ls
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: h2s
          path: |
            h2s
            tpls/
  release:
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: ls
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}